local M = {
	'nvim-telescope/telescope.nvim',
	dependencies = { 'nvim-lua/plenary.nvim' },
	lazy = false,
}

local function nkset(shortcut, cmd, opts)
	vim.keymap.set('n', shortcut, cmd, opts)
end

function M.config()
	local builtin = require('telescope.builtin')
	vim.keymap.set('n', '<C-A-p>', builtin.find_files, {})
	vim.keymap.set('n', '<C-p>', builtin.git_files, {})
	vim.keymap.set('n', '<leader>pb', builtin.buffers, {})
	vim.keymap.set('n', '<leader>ps', function()
		builtin.gre_string({ search = vim.fn.input("Grep > ") })
	end)
	vim.keymap.set('n', '<leader>vh', builtin.help_tags, {})

	-- Telescope Mappings
	local builtin = require('telescope.builtin')
	nkset('C-p', function ()
		builtin.git_files()
	end)
	nkset('C-A-p', function ()
		builtin.live_grep()
	end)
	nkset('<leader>fb', function ()
		builtin.buffers()
	end)
	nkset('<leader>fc', function ()
		builtin.commands()
	end)
	nkset('<leader>fch', function ()
		builtin.command_history()
	end)
	nkset('<leader>fsh', function ()
		builtin.search_history()
	end)
	nkset('<leader>fm', function ()
		builtin.marks()
	end)
	nkset('<leader>fcs', function ()
		builtin.colorscheme()
	end)
	nkset('<leader>fqf', function ()
		builtin.quickfix()
	end)
	nkset('<leader>fvo', function ()
		builtin.vim_options()
	end)
	nkset('<leader>fr', function ()
		builtin.registers()
	end)
	nkset('<leader>fss', function ()
		builtin.spell_suggest()
	end)
	nkset('<leader>fk', function ()
		builtin.keymaps()
	end)
	nkset('<leader>fp', function ()
		builtin.pickers()
	end)

	-- Telescope LSP pickers
	nkset('gr', function ()
		builtin.lsp_references()
	end)
	nkset('gic', function ()
		builtin.lsp_incoming_calls()
	end)
	nkset('goc', function ()
		builtin.lsp_outgoing_callst()
	end)
	nkset('gds', function ()
		builtin.lsp_document_symbols()
	end)
	nkset('gws', function ()
		builtin.lsp_workspace_symbols()
	end)
	nkset('gdg', function ()
		builtin.diagnostics()
	end)
	nkset('gi', function ()
		builtin.lsp_implementations()
	end)
	nkset('gd', function ()
		builtin.lsp_definitions()
	end)
	nkset('gtd', function ()
		builtin.lsp_type_definitions()
	end)

	-- Telescope Git
	nkset('<leader>gc', function ()
		builtin.git_commits()
	end)
	nkset('<leader>gbc', function ()
		builtin.git_bcommits()
	end)
	vim.keymap.set('v', '<leader>gc', function ()
		builtin.git_bcommits_range()
	end)
	nkset('<leader>gb', function ()
		builtin.git_branches()
	end)
	nkset('<leader>gs', function ()
		builtin.git_status()
	end)
	nkset('<leader>gst', function ()
		builtin.git_stash()
	end)

	-- Telescope Treesitter
	nkset('<leader>t', function ()
		builtin.treesitter()
	end)

end

return M
